@Library("nextgen-jenkins-library@MVP-helm") _  
secureuploadDeliveryPipeline {  
    buildCommand        = "chmod 777 gradlew && ./gradlew clean build -x test"
    // testCommand         = "./gradlew jacocoTestCoverageVerification jacocoTestReport test"
    // codeAnalysisCommand = "./gradlew sonarqube -x test"
    buildJavaVersion    = "jdk11" // java version required for build
    serviceName         = "ng-su-admin"
    ecrRegistryPattern  = "ng-su-admin"  // usually cxrewards-cds-<env>
    buildBranch         = "development" // branch which will be used primarily to build higher environments
    devBuildBranch      = "development" // branch which will be used primarily to build the dev environment
//    slackChannel        = ""
}